[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib", "./lib/cairo_contracts/src"]

[contracts]
main = ["src/main.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
